# Generated by Django 5.2.8 on 2025-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='passwordrequest',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('otp_sent', 'OTP Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
